### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by keenan35i** [KumarSunil007/phonegap-jack-reader-plugin#4]
issue with: com.deftsoft.org.jack.reader.JackReader.ReadCard(SwipeResult);
building with phonegap but there is no "com.deftsoft" object

**Comment by Darkmadda** [comment]
I had the same problem, it was a typo in the code. it should be com.betasoft.org.jackreader.JackReader.ReadCard(SwipeResult) 

the problem is "deftsoft" should be "betasoft"

**Comment by Sebdawg** [comment]
Darkmadda you got it to work?!?! That's awesome! I thought this was maybe a bad plugin. Can you help me out, please? I literally made a github account just so that I could talk to you after seeing your comment. I tired it with your link and I got this error in my console.

"Uncaught TypeError: Cannot read property 'JackReader' of undefined"

How do I define the jackreader and what am I doing wrong?

**Comment by Darkmadda** [comment]
there is a bug in the code example that you are probably running in to (I haven't had a chance to push the fix). Really it's just a typo. in the example of the readme the code:
com.deftsoft.org.jack.reader.JackReader
should be :
com.betasoft.org.jack.reader.JackReader.
(deftsoft->betasoft)
That is what fixed the problem for me.

Currently my problem is in sourcing the credit card readers. As far as i can tell the square readers that are available from square now encrypt the data before it is sent to the audio port. I found some chinese knockoffs and i'm waiting for them to arrive i'm hoping they are the old style that are unencrypted.

**Comment by KumarSunil007** [comment]
fixed.
